### ISSUE TITLE
Error on v2.25.1

### ISSUE THREAD

**Issue by agiraldie** [XxBAJNOKxX/Microsoft-Reward-Chrome-Ext#2]
![Screenshot_250](https://github.com/XxBAJNOKxX/Microsoft-Reward-Chrome-Ext/assets/45974979/4ef3b0ca-c219-4dc3-8bbd-0390f54b51d6)

tried on edge and chrome, got same error

**Comment by XxBAJNOKxX** [comment]
Hi, sorry, can we talk on discord or somewhere else?

**Comment by XxBAJNOKxX** [comment]
Hi, sorry, can we talk on discord or somewhere else?

**Comment by P1st0nBr0ke** [comment]
Same error here.

**Comment by davidkra230** [comment]
> ![Screenshot_250](https://user-images.githubusercontent.com/45974979/282359782-4ef3b0ca-c219-4dc3-8bbd-0390f54b51d6.png)
> 
> tried on edge and chrome, got same error

Not only are you inspecting the popup but, the first error is thrown due to csp which is a problem for microsoft and the other two are from the iframe, also a microsoft problem.

For us to see the what the actual error/problem is, please open the extension details which looks like this:
![Untitled](https://github.com/XxBAJNOKxX/Microsoft-Reward-Chrome-Ext/assets/71524811/4bb91a6c-a370-462f-8595-d45f229bc090)
And click the "background page" button/link under "Inspect views"

After you do that, please attach an image of the console tab in the devtools window that had opened.

**Comment by agiraldie** [comment]
![Screenshot_251](https://github.com/XxBAJNOKxX/Microsoft-Reward-Chrome-Ext/assets/45974979/35abfc0c-b9da-4230-be1e-ac17d21bfe22)

**Comment by XxBAJNOKxX** [comment]
This is not the latest version. There was an accidental typo, it was fixed in the latest version.

**Comment by XxBAJNOKxX** [comment]
This is not the latest version. There was an accidental typo, it was fixed in the latest version.

**Comment by agiraldie** [comment]
im using 2.25.1

**Comment by XxBAJNOKxX** [comment]
Try using [this](https://github.com/XxBAJNOKxX/Microsoft-Reward-Chrome-Ext/releases/tag/v2.25.1.1) version: [v2.25.1.1](https://github.com/XxBAJNOKxX/Microsoft-Reward-Chrome-Ext/releases/tag/v2.25.1.1)

**Comment by agiraldie** [comment]
[
![Screenshot_253](https://github.com/XxBAJNOKxX/Microsoft-Reward-Chrome-Ext/assets/45974979/1127137e-0ae7-4927-9860-fb711b514305)
](url)

its working now. Thanks !

**Comment by davidkra230** [comment]
You're welcome!
